### PR TITLE
151 

### PR DESCRIPTION
**Pull request by BitByBen**
${o}${H} => ${o+H} saves 2 characters.

### CODE REVIEW

**Comment by BitByBen** [comment]
Also pulling H to be defined outside of the string template and using bracket notation to access innerHTML saves another 2 characters.

**Comment by xem** [comment]
Wow, thanks!

I mentioned you in the credits and here: https://twitter.com/MaximeEuziere/status/1342738025382600704

**Comment by BitByBen** [comment]
Just saw this. It's actually benjamin_js on twitter. I should probably change my Github to prevent the confusion.

**Comment by xem** [comment]
Oops damn.

**Pull request closed without merging**
